### ISSUE TITLE
Not sure code does what it implies...

### ISSUE THREAD

**Issue by sbromberger** [proflage/2015-julia-hands-on#1]
in https://github.com/proflage/2015-julia-hands-on/blob/master/distributed_computing_with_julia.ipynb - [In 6]:

> Let's run some simple function on all workers. The following code calls the myid() function on all workers:
> In [6]:
> println("Hi, it's the Master (process ID=$(myid())) listing the workers...")
> for pid in workers()
>     println("Listing worker #", pid)
> end
> Hi, it's the Master (process ID=1) listing the workers...
> Listing worker #2
> Listing worker #3

Doesn't actually execute code in the worker processes - the `println` is executing on the master process, and just printing out the output of `workers()`. `myid()` is not called on any process but the master.

**Comment by lagefreitas** [comment]
You are right, thank you! Might have come from former examples that I removed. 

Issue fixed and pushed.
